### ISSUE TITLE
Step 13 image wrong

### ISSUE THREAD

**Issue by nicogis** [MicrosoftDocs/windowsserverdocs.it-it#4]
The image in step 13 has : 'Install Windows Server 2019 ...' . It should be 'Install Windows Server 2016 ...

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 465ee446-5e41-bd72-1305-976db9c3a4ec
* Version Independent ID: f7091237-826d-1e6e-d8f3-b688205f25fd
* Content: [Aggiornare Windows Server 2012 a Windows Server 2016](https://docs.microsoft.com/it-it/windows-server/upgrade/upgrade-2012-to-2016#feedback)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012-to-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs.it-it/blob/live/WindowsServerDocs/upgrade/upgrade-2012-to-2016.md)
* Product: **windows server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by srvbpigh** [comment]
Hello, @nicogis
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @nicogis, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3914. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
